name: artikel
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  art_sweetalert: ^0.0.5
  avatar_stack: ^1.2.0
  awesome_snackbar_content: ^0.1.2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  floating_overlay: ^1.2.1
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^4.0.0
  quickalert: ^1.0.1
  shimmer: ^3.0.0
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
